# Generated by Django 6.0.2 on 2026-03-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_assigned_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
