# Generated by Django 6.0.2 on 2026-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('cycle', 'Cycle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('admin', 'Admin'), ('warehouse', 'Warehouse Manager'), ('delivery', 'Delivery Partner')], default='user', max_length=20),
        ),
    ]
