# Generated by Django 6.0.2 on 2026-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_online_user_vehicle_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bluebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/bluebooks/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/vehicles/'),
        ),
    ]
