# Generated by Django 6.0.2 on 2026-04-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='context',
            field=models.CharField(choices=[('ORDER', 'Order related (User/Rider)'), ('WAREHOUSE', 'Warehouse related (Rider/Manager)'), ('SUPPORT', 'Support related (User/Admin)')], default='ORDER', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
