# Generated by Django 6.0.2 on 2026-03-25 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Committed to pending orders'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total Physical Stock'),
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('restock', 'Restocked'), ('order', 'Order Placed (Reserved)'), ('shipped', 'Order Shipped (Deducted)'), ('canceled', 'Order Canceled (Restored)'), ('damage', 'Damaged/Expired'), ('transfer', 'Warehouse Transfer')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Impact on stock_quantity or reserved_stock')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='warehouses.inventory')),
            ],
        ),
    ]
