# Generated by Django 6.0.2 on 2026-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_inventory_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='district',
            field=models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], default='kathmandu', max_length=20),
        ),
    ]
