# Generated by Django 6.0.2 on 2026-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_coupon'),
        ('products', '0005_alter_category_image_url_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_categories',
            field=models.ManyToManyField(blank=True, help_text='If set, coupon only applies to items in these categories', related_name='exclusive_coupons', to='products.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_products',
            field=models.ManyToManyField(blank=True, help_text='If set, coupon only applies to these specific products', related_name='exclusive_coupons', to='products.product'),
        ),
    ]
