# Generated by Django 6.0.2 on 2026-03-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug_product_brand_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='images_json',
            field=models.JSONField(blank=True, default=list, help_text='Gallery Registry'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Critical Alert Threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready for Dispatch'), ('out_of_stock', 'Out of Stock')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pcs', 'Pieces')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.CharField(default='Kathmandu Hub', help_text='Primary Supply Node', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='Numeric weight/volume'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Primary Asset URL', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum Retail Price in रू', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Final Transactional Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discounted Selling Price in रू', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
